name: Code Analysis (Security, Dependencies, SonarCloud)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 3 * * 1' # Corre cada lunes a las 3 AM UTC

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- Análisis de dependencias ---
      - name: Restore and scan .NET dependencies
        run: |
          dotnet restore
          dotnet list package --vulnerable > dependencias-vulnerables.txt

      - name: Upload dependency report
        uses: actions/upload-artifact@v4
        with:
          name: dependencias-vulnerables
          path: dependencias-vulnerables.txt

      # --- Escaneo de secretos con Gitleaks ---
      - name: Secret scan with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --report-format=json --report-path=gitleaks-report.json
        continue-on-error: true

      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json

      # --- Ejecutar pruebas con cobertura ---
      - name: Run tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage"

      # --- Instalar y ejecutar ReportGenerator ---
      - name: Install reportgenerator tool
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Convert coverage report to SonarCloud format
        run: |
          reportgenerator -reports:**/coverage.cobertura.xml \
                          -targetdir:coverage-report \
                          -reporttypes:SonarQube

      # --- Cache de SonarCloud ---
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # --- Análisis con SonarCloud ---
      - name: Run SonarCloud analysis
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=quality-ms_integration-ms
            -Dsonar.organization=quality-ms
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.cs.opencover.reportsPaths=coverage-report/SonarQube.xml
